codesign -s "DropSend, Ltd" -f "Contents/MacOS/configurator"
codesign -s "DropSend, Ltd" -f "Contents/MacOS/DropSend Direct beta"
codesign -s "DropSend, Ltd" -f "Contents/MacOS/DropSendInstallationUtility"
codesign -s "DropSend, Ltd" -f "Contents/MacOS/DropSendUpdater"

codesign -s "DropSend, Ltd" -f "/Users/user/Development/Projects/DropsendDesktop/client/DropSendClient-build-desktop/DropSend Direct beta.app/Contents/MacOS/configurator"
codesign -s "DropSend, Ltd" -f "/Users/user/Development/Projects/DropsendDesktop/client/DropSendClient-build-desktop/DropSend Direct beta.app/Contents/MacOS/DropSend Direct beta"
codesign -s "DropSend, Ltd" -f "/Users/user/Development/Projects/DropsendDesktop/client/DropSendClient-build-desktop/DropSend Direct beta.app/Contents/MacOS/DropSendInstallationUtility"
codesign -s "DropSend, Ltd" -f "/Users/user/Development/Projects/DropsendDesktop/client/DropSendClient-build-desktop/DropSend Direct beta.app/Contents/MacOS/DropSendUpdater"
codesign -s "DropSend, Ltd" -f "/Users/user/Development/Projects/DropsendDesktop/client/DropSendClient-build-desktop/DropSend Direct beta.app"
